version: 2
updates:
  - package-ecosystem: npm
    directory: /apps/api
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      nestjs:
        patterns: ['@nestjs/*']
      types:
        patterns: ['@types/*']
    commit-message:
      prefix: 'chore(api-deps)'

  - package-ecosystem: npm
    directory: /apps/web
    schedule:
      interval: weekly
    open-pull-requests-limit: 10
    groups:
      react:
        patterns: ['react', 'react-dom', '@types/react*']
    commit-message:
      prefix: 'chore(web-deps)'

  - package-ecosystem: docker
    directory: /apps/api
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore(docker)'

  - package-ecosystem: docker
    directory: /apps/web
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore(docker)'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: 'chore(ci)'
